version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecret123!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: AppointmentManager.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AppointmentManagerDb;User Id=sa;Password=SuperSecret123!;TrustServerCertificate=True;
      - RabbitMq__Host=rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: AppointmentManager.Worker/Dockerfile
    environment:
      - RabbitMq__Host=rabbitmq
    depends_on:
      - rabbitmq

volumes:
  sqlvolume:
